### ISSUE TITLE
Pivot table failure: ":"' ' is an unexpected token. The expected token is ';'

### ISSUE THREAD

**Issue by amoroso81** [visualon/epplus#191]
When creating a pivottable for data fields which contains Chinese characters, I have this exception:
[test.xlsx](https://github.com/user-attachments/files/17956335/test.xlsx)
   in System.Xml.XmlTextReaderImpl.Throw(Exception e)
   in System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   in System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   in System.Xml.XmlTextReaderImpl.ParseAttributes()
   in System.Xml.XmlTextReaderImpl.ParseElement()
   in System.Xml.XmlTextReaderImpl.ParseElementContent()
   in System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   in System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   in System.Xml.XmlDocument.Load(XmlReader reader)
   in OfficeOpenXml.Table.PivotTable.ExcelPivotCacheDefinition..ctor(XmlNamespaceManager ns, ExcelPivotTable pivotTable, ExcelRangeBase sourceAddress, Int32 tblId)
   in OfficeOpenXml.Table.PivotTable.ExcelPivotTable..ctor(ExcelWorksheet sheet, ExcelAddressBase address, ExcelRangeBase sourceAddress, String name, Int32 tblId)
   in OfficeOpenXml.Table.PivotTable.ExcelPivotTableCollection.Add(ExcelAddressBase Range, ExcelRangeBase Source, String Name)
   in Vittoria.Models.Dashboard.AbstractWidgetPlugin.RenderPivot(ExcelRangeBase dataRange, ExcelWorksheet wsPivot) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria.Acl.Mvc\Facade\Dashboard\Plugins\AbstractWidgetPlugin.cs:riga 487
   in Vittoria.Models.Dashboard.AbstractWidgetPlugin.GetPartialExportBase[T](List`1 filters, DashboardPartialExportDto dto, String dashboardName, String sheetName, String fileName) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria.Acl.Mvc\Facade\Dashboard\Plugins\AbstractWidgetPlugin.cs:riga 446
   in Vittoria.Models.Dashboard.WidgetHsKpiTemplate.GetPartialExportInfo(List`1 filters, DashboardPartialExportDto dto) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Models\Dashboard\Plugins\WidgetHsKpiTemplate.cs:riga 548
   in Vittoria.Models.Reports.Dashboard.DashboardWidgetPartialExportTemplate.CreateDownloadInfo(DashboardItem item, WidgetPluginInfo pluginInfo, List`1 filters) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Models\Reports\Dashboard\DashboardWidgetPartialExportTemplate.cs:riga 20
   in Vittoria.Models.Reports.Dashboard.AbstractDashboardWidgetExportTemplate.LoadDownloadInfoByDashboardItemInfoId(Int32 id) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Models\Reports\Dashboard\AbstractDashboardWidgetExportTemplate.cs:riga 64
   in Vittoria.Models.Reports.Dashboard.AbstractDashboardWidgetExportTemplate.GetCustomBytes(IUnitOfWork u, AbstractReportViewModel vm, Dictionary`2 localizationDictionary) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Models\Reports\Dashboard\AbstractDashboardWidgetExportTemplate.cs:riga 44
   in Vittoria.Services.ReportBuilderService.Build(IReportTemplate report, AbstractReportViewModel vm, String fileName, String localeCode, String localizationMainPageKey) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Services\Reports\ReportBuilderService.cs:riga 141
   in Vittoria.Services.ReportBuilderService.BuildAndWrite(IReportTemplate report, AbstractReportViewModel vm, String path, String fileName, String localeCode, String localizationMainPageKey, IFileManager fileManager) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Services\Reports\ReportBuilderService.cs:riga 74
   in Vittoria.Controllers.AbstractReportsController.ExecuteReportAndWriteFile(AbstractReportViewModel vm, String path, String fileName, ReportSessionInfoModel reportSessionInfoModel, IUnityContainer container) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Controllers\AbstractReportsController.cs:riga 314
   in Vittoria.Controllers.AbstractReportsController.ExecuteJob(Int32 reportsArchiveId, AbstractReportViewModel vm, String path, String fileName, ReportSessionInfoModel reportSessionInfoModel) in C:\inetpub\wwwroot\VittoriaWEB-branch\Vittoria\Controllers\AbstractReportsController.cs:riga 75

The issue is similar to https://github.com/JanKallman/EPPlus/issues/360 
Is it related to encoding? I attached the sheet containing the problematic data.
Please let me know if you need more infos. Thanks.

**Comment by viceice** [comment]
This project will be archived soon
